name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Validate tag on main
      shell: pwsh
      run: |
        git checkout main
        $mainsha = $(git show-ref refs/heads/main --hash)
        $tagsha = $(git show-ref ${{ github.ref }} --hash)

        Write-Output "refs/heads/main: $mainsha"
        Write-Output "${{ github.ref }}: $tagsha"

        if ($mainsha -ne $tagsha) {
          Write-Error "tag must match HEAD of main"
          exit 1
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Artifacts
      run: ./publish.ps1
      shell: pwsh
      env:
        CLI_VERSION: ${{ github.ref }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/win-x64/dylan-windows-amd64.exe
          ./dist/linux-x64/dylan-linux-amd64
          ./dist/osx-x64/dylan-darwin-amd64