name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Artifacts
      run: ./publish.ps1
      shell: pwsh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/win-x64/dylan-windows-amd64.exe
          ./dist/linux-x64/dylan-linux-amd64
          ./dist/osx-x64/dylan-darwin-amd64